apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - dev-ns.yml

namespace: dev
namePrefix: dev-

configMapGenerator:
  - name: nginx
    envs:
      - nginx.env

images:
  - name: nginx
    newTag: "1.29"
  - name: php
    newTag: "8.4-fpm"

labels:
  - pairs:
      env: dev
